### ISSUE TITLE
Add a "We've closed operations" note to all GitHub repositories

### ISSUE THREAD

**Issue by paulproteus** [openhatch/winddown#1]

**Comment by paulproteus** [comment]
I think @ehashman was working on this already.

**Comment by ehashman** [comment]
I did this on oh-mainline (https://github.com/openhatch/oh-mainline/commit/df26e2407cc3f00f45ba441f9021d31aa2d02742) but not elsewhere. I don't think we've seen any new contributions on other repos in the last year... or at least, not on the ones I have commit access to.

**Comment by paulproteus** [comment]
sgtm

I've renamed the OpenHatch org in GitHub, which is good enough for me.

![screenshot from 2018-08-12 14-41-39](https://user-images.githubusercontent.com/25457/44006720-e28868b6-9e3d-11e8-8dfe-5b3a513d0a7f.png)
